"""add GitHub OAuth token expiration fields

Revision ID: 3e58a6eb699a
Revises: 553a7ddf4183
Create Date: 2026-08-10 21:00:03.670131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e58a6eb699a'
down_revision: Union[str, Sequence[str], None] = '553a7ddf4183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_connections', sa.Column('refresh_token', sa.String(length=512), nullable=False))
    op.add_column('github_connections', sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('github_connections', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_connections', 'refresh_token_expires_at')
    op.drop_column('github_connections', 'access_token_expires_at')
    op.drop_column('github_connections', 'refresh_token')
    # ### end Alembic commands ###
